import { Metadata } from "next";
import { CONFIG } from "src/app/global-config";
import { InvoiceListView } from "src/sections/dashboard/invoice/view";
import { InvoiceCreateEditView } from "src/sections/dashboard/invoice/view/invoice-create-edit-view";

// ------------------------------------------------------------------

export const metadata: Metadata = {
  title: `Buat invoice | Dashboard - ${CONFIG.appName}`,
  description: "Generated by create next app",
};

// ------------------------------------------------------------------

export default function Page() {
  return <InvoiceCreateEditView />;
}
